import * as stylex from '@stylexjs/stylex';

export const inboxLayoutVars = {
  headerHeight: '152px',
  footerHeight: '84px',
  rowHeight: '92px',
  listMinWidth: '280px',
  listMaxWidth: '360px',
  metaMinWidth: '300px',
  metaMaxWidth: '420px',
  drawerWidth: '400px',
  dividerColor: 'rgba(12, 27, 26, 0.14)',
  rowHover: 'rgba(12, 27, 26, 0.04)',
  rowSelected: 'rgba(15, 118, 110, 0.12)',
  accent: '#0f766e',
  toolbarControlHeight: '54px',
  toolbarControlBorder: '#c7d2d9',
};

export const inboxStyles = stylex.create({
  root: {
    display: 'grid',
    gridTemplateRows: `${inboxLayoutVars.headerHeight} minmax(0, 1fr) ${inboxLayoutVars.footerHeight}`,
    minHeight: '100vh',
    backgroundColor: '#ffffff',
    color: '#0c1b1a',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  header: {
    minHeight: inboxLayoutVars.headerHeight,
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '12px 16px',
    display: 'grid',
    gap: '10px',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    position: 'sticky',
    top: 0,
    zIndex: 20,
  },
  headerTopRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '12px',
    paddingBottom: '6px',
  },
  horizontalDivider: {
    height: '1px',
    width: '100%',
    backgroundColor: inboxLayoutVars.dividerColor,
  },
  pageTabs: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    overflowX: 'auto',
    paddingBottom: '2px',
  },
  pageTab: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    textDecoration: 'none',
    padding: '7px 12px',
    borderRadius: '999px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    color: '#0f766e',
    backgroundColor: '#ffffff',
    fontWeight: 600,
    whiteSpace: 'nowrap',
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '2px',
    },
  },
  pageTabActive: {
    color: '#0c1b1a',
    backgroundColor: 'rgba(15, 118, 110, 0.14)',
    borderColor: '#0f766e',
  },
  headerTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 600,
  },
  toolbarRow: {
    display: 'flex',
    alignItems: 'stretch',
    alignContent: 'center',
    gap: '8px',
    flexWrap: 'nowrap',
    overflowX: 'auto',
    overflowY: 'hidden',
    position: 'relative',
    paddingTop: '6px',
    paddingBottom: '8px',
    minHeight: inboxLayoutVars.toolbarControlHeight,
  },
  controlsGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginLeft: 'auto',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  accountName: {
    fontSize: '13px',
    color: '#284b63',
    fontWeight: 600,
  },
  select: {
    padding: '6px 10px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    backgroundColor: '#ffffff',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  filterSelectWrap: {
    position: 'relative',
    minWidth: '280px',
    flexShrink: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#9aa9b5',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    boxShadow: '0 0 0 1px #c8d2da',
    ':focus-within': {
      outline: '2px solid #0f766e',
      outlineOffset: '2px',
    },
  },
  filterSelectButton: {
    width: '100%',
    minHeight: inboxLayoutVars.toolbarControlHeight,
    textAlign: 'left',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#ffffff',
    padding: '7px 10px',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    ':focus-visible': { outline: 'none' },
  },
  filterSelectTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#0c1b1a',
    lineHeight: '1.2',
  },
  filterSelectDescription: {
    fontSize: '11px',
    color: '#5b7287',
    lineHeight: '1.2',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  toolbarSelectWrap: {
    position: 'relative',
    minWidth: '210px',
    flexShrink: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#9aa9b5',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    boxShadow: '0 0 0 1px #c8d2da',
    ':focus-within': {
      outline: '2px solid #0f766e',
      outlineOffset: '2px',
    },
  },
  toolbarSelectButton: {
    width: '100%',
    minHeight: inboxLayoutVars.toolbarControlHeight,
    textAlign: 'left',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#ffffff',
    padding: '8px 10px',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    ':focus-visible': { outline: 'none' },
  },
  toolbarSelectTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#0c1b1a',
    lineHeight: '1.2',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  toolbarSelectDescription: {
    fontSize: '11px',
    color: '#5b7287',
    lineHeight: '1.2',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  selectText: {
    display: 'grid',
    gap: '2px',
    minWidth: 0,
  },
  selectCaret: {
    color: '#5b7287',
    fontSize: '14px',
    lineHeight: '1',
    fontWeight: 700,
  },
  filterMenu: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    zIndex: 30,
    width: 'min(360px, calc(100vw - 24px))',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    borderRadius: '10px',
    backgroundColor: '#ffffff',
    boxShadow: '0 8px 24px rgba(12, 27, 26, 0.16)',
    padding: '6px',
    display: 'grid',
    gap: '4px',
  },
  filterMenuItem: {
    border: 'none',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    textAlign: 'left',
    padding: '8px',
    display: 'grid',
    gap: '2px',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: '#f3f7f9',
    },
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '1px',
    },
  },
  filterMenuItemSelected: {
    backgroundColor: '#e7f7f2',
  },
  filterMenuItemTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#0c1b1a',
    lineHeight: '1.2',
  },
  filterMenuItemDescription: {
    fontSize: '11px',
    color: '#5b7287',
    lineHeight: '1.2',
  },
  toolbarCheckLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    minHeight: inboxLayoutVars.toolbarControlHeight,
    padding: '0 2px',
    fontSize: '12px',
    color: '#284b63',
    flexShrink: 0,
  },
  toolbarSearch: {
    minHeight: inboxLayoutVars.toolbarControlHeight,
    flexShrink: 0,
    minWidth: '320px',
  },
  toolbarButton: {
    minHeight: inboxLayoutVars.toolbarControlHeight,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  liveIndicatorAligned: {
    minHeight: inboxLayoutVars.toolbarControlHeight,
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
  },
  input: {
    padding: '7px 10px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    minWidth: '220px',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  toggleButton: {
    padding: '8px 12px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    backgroundColor: '#ffffff',
    color: '#0f766e',
    fontWeight: 600,
    cursor: 'pointer',
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '2px',
    },
  },
  toggleButtonActive: {
    backgroundColor: 'rgba(15, 118, 110, 0.12)',
    borderColor: '#0f766e',
  },
  conversationToggle: {
    display: 'inline-flex',
    '@media (min-width: 960px)': {
      display: 'none',
    },
  },
  panes: {
    minHeight: 0,
    height: `calc(100vh - ${inboxLayoutVars.headerHeight} - ${inboxLayoutVars.footerHeight})`,
    display: 'grid',
    gridTemplateColumns: '1fr',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: inboxLayoutVars.dividerColor,
    '@media (min-width: 960px)': {
      gridTemplateColumns: `minmax(${inboxLayoutVars.listMinWidth}, ${inboxLayoutVars.listMaxWidth}) minmax(0, 1fr)`,
    },
    '@media (min-width: 1280px)': {
      gridTemplateColumns: `minmax(${inboxLayoutVars.listMinWidth}, ${inboxLayoutVars.listMaxWidth}) minmax(0, 1fr) minmax(${inboxLayoutVars.metaMinWidth}, ${inboxLayoutVars.metaMaxWidth})`,
    },
  },
  pane: {
    minHeight: 0,
    overflow: 'auto',
    backgroundColor: '#ffffff',
  },
  inspectorPane: {
    overflow: 'hidden',
  },
  paneDividerRight: {
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: inboxLayoutVars.dividerColor,
  },
  listPane: {
    display: 'none',
    '@media (min-width: 960px)': {
      display: 'block',
    },
  },
  messagesPane: {
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr) auto',
    overflow: 'hidden',
    position: 'relative',
  },
  metaPane: {
    display: 'none',
    '@media (min-width: 1280px)': {
      display: 'block',
    },
  },
  metaPaneCollapsed: {
    '@media (min-width: 1280px)': {
      display: 'none',
    },
  },
  list: {
    margin: 0,
    padding: 0,
    listStyle: 'none',
    display: 'block',
  },
  listEmpty: {
    padding: '16px',
    color: '#284b63',
    fontSize: '14px',
  },
  row: {
    width: '100%',
    height: inboxLayoutVars.rowHeight,
    minHeight: inboxLayoutVars.rowHeight,
    maxHeight: inboxLayoutVars.rowHeight,
    border: 'none',
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
    margin: 0,
    backgroundColor: '#ffffff',
    textAlign: 'left',
    padding: '12px 16px 12px 20px',
    display: 'grid',
    gridTemplateRows: 'auto auto minmax(0, 1fr)',
    gap: '4px',
    cursor: 'pointer',
    position: 'relative',
    borderRadius: 0,
    ':hover': {
      backgroundColor: inboxLayoutVars.rowHover,
    },
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '-2px',
      zIndex: 1,
    },
  },
  rowItem: {
    position: 'relative',
  },
  rowMainButton: {
    paddingRight: '72px',
  },
  rowAuditDock: {
    position: 'absolute',
    top: '8px',
    right: '10px',
    zIndex: 2,
  },
  rowAuditButton: {
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    borderRadius: '999px',
    backgroundColor: '#ffffff',
    color: '#284b63',
    fontSize: '11px',
    fontWeight: 600,
    padding: '3px 8px',
    cursor: 'pointer',
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '2px',
    },
  },
  rowSelected: {
    backgroundColor: inboxLayoutVars.rowSelected,
    fontWeight: 600,
    '::before': {
      content: '""',
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: '3px',
      backgroundColor: inboxLayoutVars.accent,
    },
  },
  rowTitle: {
    fontSize: '14px',
    fontWeight: 600,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  rowTitleSelected: {
    color: '#083c39',
    fontWeight: 700,
  },
  rowMeta: {
    fontSize: '12px',
    color: '#284b63',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  rowSnippet: {
    fontSize: '13px',
    color: '#0c1b1a',
    display: '-webkit-box',
    WebkitLineClamp: '2',
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '1.25',
  },
  section: {
    padding: '14px 16px',
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
  },
  messageHeaderRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
  },
  messageHeaderActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  auditedChip: {
    display: 'inline-flex',
    marginTop: '6px',
    padding: '2px 8px',
    borderRadius: '999px',
    border: '1px solid #6ee7b7',
    backgroundColor: '#ecfdf5',
    color: '#065f46',
    fontSize: '11px',
    fontWeight: 600,
  },
  messageHeaderInfo: {
    minWidth: 0,
  },
  sectionNoBorder: {
    borderBottom: 'none',
  },
  sectionTitle: {
    margin: 0,
    marginBottom: '8px',
    fontSize: '12px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#284b63',
    fontWeight: 600,
  },
  messageTimeline: {
    display: 'grid',
    gap: '10px',
    padding: '16px',
    alignContent: 'start',
    minHeight: 0,
    overflow: 'auto',
  },
  message: {
    borderRadius: '10px',
    padding: '10px 12px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    maxWidth: '80%',
    display: 'grid',
    gap: '6px',
  },
  inbound: {
    backgroundColor: '#f8f5f2',
    justifySelf: 'start',
  },
  outbound: {
    backgroundColor: '#e7f7f2',
    justifySelf: 'end',
  },
  messageMeta: {
    fontSize: '12px',
    color: '#284b63',
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '2px',
  },
  chipButton: {
    padding: '2px 8px',
    borderRadius: '999px',
    fontSize: '11px',
    backgroundColor: '#eef2ff',
    color: '#3730a3',
    border: 'none',
    cursor: 'pointer',
  },
  detailCard: {
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    borderRadius: '10px',
    padding: '12px',
    display: 'grid',
    gap: '6px',
    backgroundColor: '#ffffff',
  },
  inspectorContainer: {
    minHeight: 0,
    height: '100%',
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
  },
  tabBar: {
    position: 'sticky',
    top: 0,
    zIndex: 2,
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
    backgroundColor: '#ffffff',
  },
  tab: {
    border: 'none',
    borderRight: `1px solid ${inboxLayoutVars.dividerColor}`,
    borderRadius: 0,
    padding: '10px 12px',
    backgroundColor: '#ffffff',
    fontWeight: 600,
    color: '#284b63',
    textAlign: 'center',
    cursor: 'pointer',
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '-2px',
    },
  },
  tabSelected: {
    backgroundColor: '#eef7f4',
    color: '#0c1b1a',
    boxShadow: 'inset 0 -2px 0 #0f766e',
  },
  panelScroll: {
    minHeight: 0,
    overflow: 'auto',
  },
  emptyState: {
    padding: '16px',
    color: '#284b63',
    fontSize: '14px',
  },
  templatesHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
  },
  templateList: {
    display: 'grid',
    gap: '10px',
  },
  templateRowHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '8px',
  },
  templatePreview: {
    fontSize: '13px',
    color: '#0c1b1a',
    display: '-webkit-box',
    WebkitLineClamp: '2',
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '1.3',
  },
  fieldLabel: {
    display: 'grid',
    gap: '6px',
    fontSize: '13px',
    color: '#284b63',
  },
  templateInput: {
    width: '100%',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '8px 10px',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  templateTextArea: {
    width: '100%',
    minHeight: '120px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '10px',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  templateError: {
    color: '#7c2d12',
    backgroundColor: '#fff1ec',
    border: '1px solid #fca5a5',
    padding: '8px 10px',
    fontSize: '13px',
  },
  templateStatus: {
    color: '#065f46',
    backgroundColor: '#ecfdf5',
    border: '1px solid #6ee7b7',
    padding: '8px 10px',
    fontSize: '13px',
  },
  previewPanel: {
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '10px',
    backgroundColor: '#ffffff',
    display: 'grid',
    gap: '8px',
  },
  previewHeader: {
    fontSize: '13px',
    color: '#0c1b1a',
  },
  previewText: {
    margin: 0,
    whiteSpace: 'pre-wrap',
    fontFamily: '"IBM Plex Mono", ui-monospace, SFMono-Regular, monospace',
    fontSize: '12px',
    lineHeight: '1.4',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '8px',
    backgroundColor: '#f8fafc',
    maxHeight: '220px',
    overflow: 'auto',
  },
  warningBox: {
    color: '#7c2d12',
    backgroundColor: '#fff7ed',
    border: '1px solid #fdba74',
    padding: '8px',
    fontSize: '12px',
  },
  errorBox: {
    color: '#7f1d1d',
    backgroundColor: '#fef2f2',
    border: '1px solid #fca5a5',
    padding: '8px',
    fontSize: '12px',
  },
  templateHelpers: {
    borderTop: `1px solid ${inboxLayoutVars.dividerColor}`,
    paddingTop: '10px',
    display: 'grid',
    gap: '10px',
  },
  templateHelpersTitle: {
    fontSize: '12px',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: '#284b63',
    fontWeight: 600,
  },
  templateHelpersHint: {
    fontSize: '12px',
    color: '#5b7287',
    marginTop: '-4px',
  },
  templateHelperGroup: {
    display: 'grid',
    gap: '6px',
  },
  templateHelperHeading: {
    fontSize: '12px',
    color: '#0c1b1a',
    fontWeight: 600,
  },
  templateHelperChips: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  templateHelperChip: {
    borderRadius: 0,
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    backgroundColor: '#ffffff',
    color: '#284b63',
    padding: '4px 8px',
    fontSize: '12px',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: '#f3f6f9',
    },
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '1px',
    },
  },
  composer: {
    padding: '12px 16px 16px',
    borderTop: `1px solid ${inboxLayoutVars.dividerColor}`,
    display: 'grid',
    gap: '8px',
    backgroundColor: '#ffffff',
    position: 'relative',
    zIndex: 1,
  },
  textarea: {
    width: '100%',
    minHeight: '90px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '10px',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  actionsRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  auditAnchor: {
    position: 'relative',
  },
  auditPopover: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    right: 0,
    width: '280px',
    maxWidth: 'min(280px, calc(100vw - 24px))',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    borderRadius: '10px',
    backgroundColor: '#ffffff',
    padding: '10px',
    zIndex: 40,
    boxShadow: '0 8px 28px rgba(12, 27, 26, 0.18)',
    display: 'grid',
    gap: '8px',
  },
  auditPopoverTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#0c1b1a',
  },
  auditPopoverLabel: {
    fontSize: '11px',
    color: '#284b63',
  },
  auditReasonRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  auditReasonChip: {
    borderRadius: '999px',
    border: '1px solid rgba(12, 27, 26, 0.14)',
    padding: '2px 8px',
    fontSize: '11px',
    color: '#284b63',
    backgroundColor: '#f8fafc',
  },
  auditTextArea: {
    width: '100%',
    minHeight: '72px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '8px',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
    fontSize: '12px',
  },
  liveIndicator: {
    fontSize: '12px',
    color: '#284b63',
    whiteSpace: 'nowrap',
  },
  footer: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: inboxLayoutVars.dividerColor,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: inboxLayoutVars.dividerColor,
    backgroundColor: '#ffffff',
    padding: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: '12px',
    color: '#284b63',
  },
  drawer: {
    position: 'fixed',
    top: 0,
    bottom: 0,
    right: 0,
    width: `min(${inboxLayoutVars.drawerWidth}, calc(100vw - 24px))`,
    maxWidth: '100vw',
    backgroundColor: '#ffffff',
    borderLeft: `1px solid ${inboxLayoutVars.dividerColor}`,
    zIndex: 60,
    transform: 'translateX(100%)',
    transition: 'transform 180ms ease',
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    boxShadow: '0 18px 60px rgba(12, 27, 26, 0.2)',
    outline: 'none',
  },
  drawerLeft: {
    left: 0,
    right: 'auto',
    transform: 'translateX(-100%)',
    borderLeft: 'none',
    borderRight: `1px solid ${inboxLayoutVars.dividerColor}`,
  },
  drawerOpen: {
    transform: 'translateX(0)',
  },
  drawerHeader: {
    padding: '12px 14px',
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  drawerBody: {
    minHeight: 0,
    overflow: 'auto',
  },
  inspectorDrawerBody: {
    overflow: 'hidden',
  },
  scrim: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(12, 27, 26, 0.45)',
    opacity: 0,
    pointerEvents: 'none',
    transition: 'opacity 180ms ease',
    zIndex: 50,
  },
  scrimOpen: {
    opacity: 1,
    pointerEvents: 'auto',
  },
  hideOnSmall: {
    display: 'none',
    '@media (min-width: 960px)': {
      display: 'inline-flex',
    },
  },
  metaScroll: {
    padding: '14px 16px 16px',
    display: 'grid',
    gap: '12px',
    alignContent: 'start',
  },
});
