import * as stylex from '@stylexjs/stylex';

export const inboxLayoutVars = {
  headerHeight: '112px',
  footerHeight: '84px',
  rowHeight: '92px',
  listMinWidth: '280px',
  listMaxWidth: '360px',
  metaMinWidth: '300px',
  metaMaxWidth: '420px',
  drawerWidth: '400px',
  dividerColor: 'rgba(12, 27, 26, 0.12)',
  rowHover: 'rgba(12, 27, 26, 0.04)',
  rowSelected: 'rgba(15, 118, 110, 0.12)',
  accent: '#0f766e',
};

export const inboxStyles = stylex.create({
  root: {
    display: 'grid',
    gridTemplateRows: `${inboxLayoutVars.headerHeight} minmax(0, 1fr) ${inboxLayoutVars.footerHeight}`,
    minHeight: '100vh',
    backgroundColor: '#ffffff',
    color: '#0c1b1a',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  header: {
    minHeight: inboxLayoutVars.headerHeight,
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '12px 16px',
    display: 'grid',
    gap: '10px',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    position: 'sticky',
    top: 0,
    zIndex: 20,
  },
  headerTopRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '12px',
  },
  pageTabs: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    overflowX: 'auto',
    paddingBottom: '2px',
  },
  pageTab: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    textDecoration: 'none',
    padding: '7px 12px',
    borderRadius: '999px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    color: '#0f766e',
    backgroundColor: '#ffffff',
    fontWeight: 600,
    whiteSpace: 'nowrap',
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '2px',
    },
  },
  pageTabActive: {
    color: '#0c1b1a',
    backgroundColor: 'rgba(15, 118, 110, 0.14)',
    borderColor: '#0f766e',
  },
  headerTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 600,
  },
  toolbarRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    overflowX: 'auto',
    paddingBottom: '2px',
  },
  controlsGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  select: {
    padding: '6px 10px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    backgroundColor: '#ffffff',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  input: {
    padding: '7px 10px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    minWidth: '220px',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  toggleButton: {
    padding: '8px 12px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    backgroundColor: '#ffffff',
    color: '#0f766e',
    fontWeight: 600,
    cursor: 'pointer',
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '2px',
    },
  },
  toggleButtonActive: {
    backgroundColor: 'rgba(15, 118, 110, 0.12)',
    borderColor: '#0f766e',
  },
  conversationToggle: {
    display: 'inline-flex',
    '@media (min-width: 960px)': {
      display: 'none',
    },
  },
  panes: {
    minHeight: 0,
    height: `calc(100vh - ${inboxLayoutVars.headerHeight} - ${inboxLayoutVars.footerHeight})`,
    display: 'grid',
    gridTemplateColumns: '1fr',
    '@media (min-width: 960px)': {
      gridTemplateColumns: `minmax(${inboxLayoutVars.listMinWidth}, ${inboxLayoutVars.listMaxWidth}) minmax(0, 1fr)`,
    },
    '@media (min-width: 1280px)': {
      gridTemplateColumns: `minmax(${inboxLayoutVars.listMinWidth}, ${inboxLayoutVars.listMaxWidth}) minmax(0, 1fr) minmax(${inboxLayoutVars.metaMinWidth}, ${inboxLayoutVars.metaMaxWidth})`,
    },
  },
  pane: {
    minHeight: 0,
    overflow: 'auto',
    backgroundColor: '#ffffff',
  },
  paneDividerRight: {
    borderRight: `1px solid ${inboxLayoutVars.dividerColor}`,
  },
  listPane: {
    display: 'none',
    '@media (min-width: 960px)': {
      display: 'block',
    },
  },
  messagesPane: {
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr) auto',
    overflow: 'hidden',
    position: 'relative',
  },
  metaPane: {
    display: 'none',
    '@media (min-width: 1280px)': {
      display: 'block',
    },
  },
  metaPaneCollapsed: {
    '@media (min-width: 1280px)': {
      display: 'none',
    },
  },
  list: {
    margin: 0,
    padding: 0,
    listStyle: 'none',
    display: 'block',
  },
  listEmpty: {
    padding: '16px',
    color: '#284b63',
    fontSize: '14px',
  },
  row: {
    width: '100%',
    height: inboxLayoutVars.rowHeight,
    minHeight: inboxLayoutVars.rowHeight,
    maxHeight: inboxLayoutVars.rowHeight,
    border: 'none',
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
    margin: 0,
    backgroundColor: '#ffffff',
    textAlign: 'left',
    padding: '12px 16px 12px 20px',
    display: 'grid',
    gridTemplateRows: 'auto auto minmax(0, 1fr)',
    gap: '4px',
    cursor: 'pointer',
    position: 'relative',
    borderRadius: 0,
    ':hover': {
      backgroundColor: inboxLayoutVars.rowHover,
    },
    ':focus-visible': {
      outline: '2px solid #0f766e',
      outlineOffset: '-2px',
      zIndex: 1,
    },
  },
  rowSelected: {
    backgroundColor: inboxLayoutVars.rowSelected,
    fontWeight: 600,
    '::before': {
      content: '""',
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: '3px',
      backgroundColor: inboxLayoutVars.accent,
    },
  },
  rowTitle: {
    fontSize: '14px',
    fontWeight: 600,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  rowTitleSelected: {
    color: '#083c39',
    fontWeight: 700,
  },
  rowMeta: {
    fontSize: '12px',
    color: '#284b63',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  rowSnippet: {
    fontSize: '13px',
    color: '#0c1b1a',
    display: '-webkit-box',
    WebkitLineClamp: '2',
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '1.25',
  },
  section: {
    padding: '14px 16px',
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
  },
  sectionNoBorder: {
    borderBottom: 'none',
  },
  sectionTitle: {
    margin: 0,
    marginBottom: '8px',
    fontSize: '12px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#284b63',
    fontWeight: 600,
  },
  messageTimeline: {
    display: 'grid',
    gap: '10px',
    padding: '16px',
    alignContent: 'start',
    minHeight: 0,
    overflow: 'auto',
  },
  message: {
    borderRadius: '10px',
    padding: '10px 12px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    maxWidth: '80%',
    display: 'grid',
    gap: '6px',
  },
  inbound: {
    backgroundColor: '#f8f5f2',
    justifySelf: 'start',
  },
  outbound: {
    backgroundColor: '#e7f7f2',
    justifySelf: 'end',
  },
  messageMeta: {
    fontSize: '12px',
    color: '#284b63',
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '2px',
  },
  chipButton: {
    padding: '2px 8px',
    borderRadius: '999px',
    fontSize: '11px',
    backgroundColor: '#eef2ff',
    color: '#3730a3',
    border: 'none',
    cursor: 'pointer',
  },
  detailCard: {
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    borderRadius: '10px',
    padding: '12px',
    display: 'grid',
    gap: '6px',
    backgroundColor: '#ffffff',
  },
  composer: {
    padding: '12px 16px 16px',
    borderTop: `1px solid ${inboxLayoutVars.dividerColor}`,
    display: 'grid',
    gap: '8px',
    backgroundColor: '#ffffff',
    position: 'relative',
    zIndex: 1,
  },
  textarea: {
    width: '100%',
    minHeight: '90px',
    borderRadius: '8px',
    border: `1px solid ${inboxLayoutVars.dividerColor}`,
    padding: '10px',
    fontFamily: '"IBM Plex Sans", "Helvetica", sans-serif',
  },
  actionsRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  liveIndicator: {
    fontSize: '12px',
    color: '#284b63',
    whiteSpace: 'nowrap',
  },
  floatingInspector: {
    position: 'absolute',
    top: '84px',
    right: '16px',
    zIndex: 5,
    boxShadow: '0 8px 24px rgba(12, 27, 26, 0.16)',
  },
  footer: {
    borderTop: `1px solid ${inboxLayoutVars.dividerColor}`,
    backgroundColor: '#ffffff',
    padding: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: '12px',
    color: '#284b63',
  },
  footerSpacer: {
    minHeight: '40px',
    minWidth: '220px',
  },
  drawer: {
    position: 'fixed',
    top: 0,
    bottom: 0,
    right: 0,
    width: `min(${inboxLayoutVars.drawerWidth}, calc(100vw - 24px))`,
    maxWidth: '100vw',
    backgroundColor: '#ffffff',
    borderLeft: `1px solid ${inboxLayoutVars.dividerColor}`,
    zIndex: 60,
    transform: 'translateX(100%)',
    transition: 'transform 180ms ease',
    display: 'grid',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    boxShadow: '0 18px 60px rgba(12, 27, 26, 0.2)',
    outline: 'none',
  },
  drawerLeft: {
    left: 0,
    right: 'auto',
    transform: 'translateX(-100%)',
    borderLeft: 'none',
    borderRight: `1px solid ${inboxLayoutVars.dividerColor}`,
  },
  drawerOpen: {
    transform: 'translateX(0)',
  },
  drawerHeader: {
    padding: '12px 14px',
    borderBottom: `1px solid ${inboxLayoutVars.dividerColor}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  drawerBody: {
    minHeight: 0,
    overflow: 'auto',
  },
  scrim: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(12, 27, 26, 0.45)',
    opacity: 0,
    pointerEvents: 'none',
    transition: 'opacity 180ms ease',
    zIndex: 50,
  },
  scrimOpen: {
    opacity: 1,
    pointerEvents: 'auto',
  },
  hideOnSmall: {
    display: 'none',
    '@media (min-width: 960px)': {
      display: 'inline-flex',
    },
  },
  metaScroll: {
    padding: '14px 16px 16px',
    display: 'grid',
    gap: '12px',
    alignContent: 'start',
  },
});
