// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/reports" | "/terms" | "/privacy" | "/*";
  };
  "routes/root.tsx": {
    id: "routes/root";
    page: "/" | "/reports" | "/terms" | "/privacy" | "/*";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/reports.tsx": {
    id: "routes/reports";
    page: "/reports";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/root": typeof import("./src/routes/root.tsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
  "routes/reports": typeof import("./src/routes/reports.tsx");
  "routes/terms": typeof import("./src/routes/terms.tsx");
  "routes/privacy": typeof import("./src/routes/privacy.tsx");
  "routes/not-found": typeof import("./src/routes/not-found.tsx");
};