// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/reports': {
    params: {};
  };
  '/*': {
    params: {
      '*': string;
    };
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/reports' | '/*';
  };
  'routes/root.tsx': {
    id: 'routes/root';
    page: '/' | '/reports' | '/*';
  };
  'routes/dashboard.tsx': {
    id: 'routes/dashboard';
    page: '/';
  };
  'routes/reports.tsx': {
    id: 'routes/reports';
    page: '/reports';
  };
  'routes/not-found.tsx': {
    id: 'routes/not-found';
    page: '/*';
  };
};

type RouteModules = {
  root: typeof import('./src/root.tsx');
  'routes/root': typeof import('./src/routes/root.tsx');
  'routes/dashboard': typeof import('./src/routes/dashboard.tsx');
  'routes/reports': typeof import('./src/routes/reports.tsx');
  'routes/not-found': typeof import('./src/routes/not-found.tsx');
};
